# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HQ Smoke Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ deploy_success ]
  workflow_dispatch:


jobs:
  build:
    name: Smoke on '${{ github.event.client_payload.environment || 'staging' }}'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r HQSmokeTests/requires.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: CCHQ Smoke Test with pytest
      env:
        DIMAGIQA_ENV: ${{ github.event.client_payload.environment }}  #${{ secrets.DIMAGIQA_URL }}
        DIMAGIQA_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
        DIMAGIQA_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}
        DIMAGIQA_MAIL_USERNAME: ${{ secrets.DIMAGIQA_MAIL_USERNAME }}
        DIMAGIQA_MAIL_PASSWORD: ${{ secrets.DIMAGIQA_MAIL_PASSWORD }}
        DIMAGIQA_BS_USER: ${{ secrets.DIMAGIQA_BS_USER }}
        DIMAGIQA_BS_KEY: ${{ secrets.DIMAGIQA_BS_KEY }}
        DIMAGIQA_STAGING_AUTH_KEY: ${{ secrets.DIMAGIQA_STAGING_AUTH_KEY }}
        DIMAGIQA_PROD_AUTH_KEY: ${{ secrets.DIMAGIQA_PROD_AUTH_KEY }}
        DIMAGIQA_INVITED_WEBUSER_PASSWORD: ${{ secrets.DIMAGIQA_INVITED_WEBUSER_PASSWORD }}

      run: |
        echo "client_payload: ${{ toJson(github.event.client_payload) }}"
        echo "NOW=$(date +'%m-%d %H:%M')" >> $GITHUB_ENV
        echo ${{env.NOW}}
        pytest -v --rootdir= HQSmokeTests/testCases -n 4 --dist=loadfile --reruns 1

    - name: CCHQ Smoke Test with pytest on Production
      if: ${{ github.event_name == 'push'}}
      env:
        DIMAGIQA_URL: ${{ secrets.DIMAGIQA_PROD_URL }}  #${{ secrets.DIMAGIQA_URL }}
        DIMAGIQA_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
        DIMAGIQA_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}
        DIMAGIQA_MAIL_USERNAME: ${{ secrets.DIMAGIQA_MAIL_USERNAME }}
        DIMAGIQA_MAIL_PASSWORD: ${{ secrets.DIMAGIQA_MAIL_PASSWORD }}
        DIMAGIQA_BS_USER: ${{ secrets.DIMAGIQA_BS_USER }}
        DIMAGIQA_BS_KEY: ${{ secrets.DIMAGIQA_BS_KEY }}
        DIMAGIQA_STAGING_AUTH_KEY: ${{ secrets.DIMAGIQA_STAGING_AUTH_KEY }}
        DIMAGIQA_PROD_AUTH_KEY: ${{ secrets.DIMAGIQA_PROD_AUTH_KEY }}
        DIMAGIQA_INVITED_WEBUSER_PASSWORD: ${{ secrets.DIMAGIQA_INVITED_WEBUSER_PASSWORD }}

      run: |
        echo "client_payload: ${{ toJson(github.event.client_payload) }}"
        echo "NOW=$(date +'%m-%d %H:%M')" >> $GITHUB_ENV
        echo ${{env.NOW}}
        pytest -v --rootdir= HQSmokeTests/testCases -n 4 --dist=loadfile --reruns 1 --html=report_prod.html

- name: Send Pass Email On Deploy Event
      uses: dawidd6/action-send-mail@v3
      if: ${{ success() && github.event_name == 'repository_dispatch' }}
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        # Required mail subject:
        subject: ${{ github.event.client_payload.environment }}  PASS - Smoke Tests[#${{github.run_number}}], ${{env.NOW}}
        # Required recipients' addresses:
        to: qa@dimagi.com, sameena.shaik@fissionlabs.com
        # Required sender full name (address can be skipped):
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        # Optional HTML body read from file:
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_pass.html
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal

    - name: Send Failure Email on Deploy Event
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() && github.event_name == 'repository_dispatch' }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: ${{ github.event.client_payload.environment }} FAIL - Smoke Tests[#${{github.run_number}}], ${{env.NOW}}
        to: qa@dimagi.com, sameena.shaik@fissionlabs.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_fail.html
        attachments: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        priority: normal

    - name: Send Failure Email on Push or Pull
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() && github.event_name != 'repository_dispatch' }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: FAIL - Smoke Tests[#${{github.run_number}}] on branch "${{ github.head_ref }}", ${{env.NOW}}
        to: qa-automation@dimagi.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_fail.html
        attachments: /home/runner/work/dimagi-qa/dimagi-qa/report.html, /home/runner/work/dimagi-qa/dimagi-qa/report_prod.html
        priority: normal

    - name: Send Pass Email on Push or Pull
      uses: dawidd6/action-send-mail@v3
      if: ${{ success() && github.event_name != 'repository_dispatch' }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: PASS - Smoke Tests[#${{github.run_number}}] on branch "${{ github.head_ref }}", ${{env.NOW}}
        to: qa-automation@dimagi.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_pass.html
        priority: normal

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-reports
        path: /home/runner/work/dimagi-qa/dimagi-qa/report*.html
        retention-days: 2