name: NY App Regression Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy_success ]

concurrency:
  group: tests-on-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: NY CICT on '${{ github.event.client_payload.environment || 'manual trigger' }}'
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.environment == 'production' || github.event.client_payload.environment == null }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r USH_Apps/NY_CICT/requirements.txt
        sudo apt-get install xvfb
        
    - name: NY App Tests
      env:
        DIMAGIQA_MAIL_USERNAME: ${{ secrets.DIMAGIQA_MAIL_USERNAME }}
        DIMAGIQA_MAIL_PASSWORD: ${{ secrets.DIMAGIQA_MAIL_PASSWORD }}
        DIMAGIQA_RF_SECRETS:  ${{ secrets.DIMAGIQA_RF_SECRETS }}
        DIMAGIQA_RF_PASSWORD:  ${{ secrets.DIMAGIQA_RF_PASSWORD }}
      run: |
        pabot --processes 13  --ordering ./USH_Apps/NY_CICT/Tests/.pabotsuitenames-ordering --outputdir ./USH_Apps/NY_CICT/Reports  ./USH_Apps/NY_CICT/Tests/*.robot



    - name: Zip Reports folder
      uses: papeloto/action-zip@v1
      if: always()
      with:
          files: ./USH_Apps/NY_CICT/Reports/
          dest: ./USH_Apps/NY_CICT/Reports.zip

    - name: Send Failure Email on Trigger
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: ${{ github.event.client_payload.environment }} - FAIL - NY App Tests (ny-staging-cdms) [#${{github.run_number}}], ${{env.NOW}}
        to: ktripathy@dimagi.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: Please find the attached report. To access screenshots, download the test results artifacted in the respective job run.
        attachments:  ${{ github.workspace }}/USH_Apps/NY_CICT/Reports/report.html
        priority: normal

    - name: Send Success Email on Trigger
      uses: dawidd6/action-send-mail@v3
      if: ${{ success() }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: ${{ github.event.client_payload.environment || 'Manual Trigger'}} - PASS - NY App Tests (ny-staging-cdms) [#${{github.run_number}}], ${{env.NOW}}
        to: qa@dimagi.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: Please find the attached report. To access screenshots, download the test results artifacted in the respective job run.
        attachments: ${{ github.workspace }}/USH_Apps/NY_CICT/Reports/report.html
        priority: normal

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-reports
        path: ${{ github.workspace }}/USH_Apps/NY_CICT/Reports.zip
